finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('finches/', views.finches_index, name='index'),
  path('finches/<int:finch_id>', views.finches_detail, name='detail'),
  path('finches/create', views.FinchCreate.as_view(), name='finches_create'),
  path('finches/<int:pk>/update', views.FinchUpdate.as_view(), name='finches_update'),
  path('finches/<int:pk>/delete', views.FinchDelete.as_view(), name='finches_delete'),
  path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding')
]

main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
  ('B', 'Breakfast'),
  ('L', 'Lunch'),
  ('D', 'Dinner'),
)
# Create your models here.
class Finch(models.Model):
  name = models.CharField(max_length=100)
  habitat = models.CharField(max_length=100)
  description = models.TextField(max_length=300)
  diet = models.CharField(max_length=100)


  def get_absolute_url(self):
    return reverse('detail', kwargs={'finch_id': self.id})
  
  def __str__(self):
    return self.name
  

class Feeding(models.Model):
  date = models.DateField('feeding date')
  meal = models.CharField(
    max_length=1,
    # add the 'choices' field option
    choices=MEALS,
    # set the default value for meal to be 'B'
    default=MEALS[0][0]
  )
  finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

  def __str__(self):
    return f'{self.get_meal_display()} on {self.date}'
  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Finch
from .forms import FeedingForm

# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def finches_index(request):
  finches = Finch.objects.all()
  return render(request, 'finches/index.html', {'finches': finches})

def finches_detail(request, finch_id):
  finch = Finch.objects.get(id=finch_id)
  feeding_form = FeedingForm()
  return render(request, 'finches/detail.html', {'finch': finch, 'feeding_form': feeding_form})

class FinchCreate(CreateView):
  model = Finch
  fields = '__all__'

class FinchUpdate(UpdateView):
  model = Finch
  fields = ['habitat', 'description', 'diet']

class FinchDelete(DeleteView):
  model = Finch
  success_url = '/finches'

def add_feeding(request, finch_id):
  # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the finch_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.finch_id = finch_id
    new_feeding.save()
  return redirect('detail', finch_id=finch_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Finch Collector</h1>
<hr>
<p>Hire the Finch Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
    href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
    rel="stylesheet"
  />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Finch Collector</title>
  </head>
  <body>
    <header class="header">
      <div class="btn header__logo-box">
        <a href="/"><img src="../static/img/Iconsmind-Outline-Bird.512.png" alt="Bird-logo"> </a>
      </div>
      <div class="header__nav-links">
        <a class='btn nav-btn' href="{% url 'about' %}">About</a>
        <a class='btn nav-btn' href="{% url 'finches_create' %}">Add New Finch</a>
        <a class='btn nav-btn' href="{% url 'index' %}">View All Finches</a>
      </div>
    </header>
    <main class="main">{% block content %} {% endblock %}</main>

    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2021 FinchCollector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %} {% block content %}
<a class="link-back" href="/finches">Back</a>
<div class="row">
  <div class="col-1-of-2">
    <div class="card__container">
      <div class="card add-finch__card">
        <div class="card__content">
          <span class="card__content-title">{{ finch.name }}</span>
          <p>Breed: {{ finch.habitat }}</p>
          <p>Description: {{ finch.description|linebreaks }}</p>
          <p>Diet: {{finch.diet}}</p>
        </div>
        <div class="add-finch__action">
          <a class="btn" href="{% url 'finches_update' finch.id %}">Edit</a>
          <a class="btn" href="{% url 'finches_delete' finch.id %}">Delete</a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-1-of-2">
    <div class="feeding">
      <form action="{% url 'add_feeding' finch.id %}" method="POST" class="feeding__form">
        {% csrf_token %}
        <!-- Render the inputs -->
        {{ feeding_form.as_p }}
        <input type="submit" class="btn btn-submit" value="Add Feeding" />
      </form>
      <table class="feeding__table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Meal</th>
          </tr>
        </thead>
        <tbody>
          {% for feeding in finch.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %} {% block content %}

<div class="card__container">
  {% for finch in finches%}
  <div class="card">
    <a href="{% url 'detail' finch.id%}">
      <div class="card__content">
        <span class="card__content-title">{{ finch.name }}</span>
        <p>Breed: {{ finch.habitat }}</p>
        <p>Description: {{ finch.description|linebreaks }}</p>
        <p>Diet: {{finch.diet}}</p>
      </div>
    </a>
  </div>
  {%endfor%}
</div>
{% endblock %}

main_app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <title>Finch Collector</title>
  </head>
  <body class="landing">
    <header class="landing-header">
      <div class="landing-logo">
        <a href="/"
          ><img
            src="../static/img/Iconsmind-Outline-Bird.512.png"
            alt="Bird-logo"
          />
        </a>
      </div>
    </header>
    <div>
      <h1>
        Finch Collector
        <h2>
          <a class="btn landing-btn" href="/finches">View Finches</a>
        </h2>
      </h1>

    </div>
  </body>
</html>

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Finch</h1>

<h4>Are you sure you want to delete <span>{{ object.name }}</span>?</h4>
  
<form action="" method="POST">
{%csrf_token%}
<input type="submit" value="Confirm" class="btn">
<a href="{% url 'detail' finch.id %}">Cancel</a>
</form>



{% endblock%}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %} {% block content %}

<div class="add-finch">
  {% if object %}
  <h1 class="add-finch__heading">Edit <span>{{object.name}}</span></h1>
  {% else %}
  <h1 class="add-finch__heading">Add Finch</h1>
  {% endif %}

  <form action="" method="POST" class="add-finch__form">
    <!-- this form submits back to the curren url-->
    {% csrf_token%}
    <table>
      {{form.as_table}}
    </table>
    <input type="submit" value="Submit" class="btn btn-submit add-finch__btn" />
  </form>
</div>

{%endblock%}